import { useCallback } from 'react'
import { wrapText, buildSVG } from './braille'

export function useSVGExport(settings) {
  const getSVGString = useCallback(() => {
    const text = settings.text
    if (!text.trim()) return null
    const lines = wrapText(text, settings.maxCols, settings.singleLine)
    const { svgMarkup } = buildSVG({
      lines,
      dotRadius:   settings.dotRadius,
      cellW:       settings.cellW,
      cellH:       settings.cellH,
      lineSpacing: settings.lineSpacing,
      margin:      settings.margin,
      colorDot:    settings.colorDot,
      colorEmpty:  settings.colorEmpty,
      showEmpty:   settings.showEmpty,
      showGuide:   settings.showGuide,
    })
    return `<?xml version="1.0" encoding="UTF-8"?>\n<!-- Generated by Braille Converter  -->\n${svgMarkup}`
  }, [settings])

  const exportSVG = useCallback(() => {
    const svg = getSVGString()
    if (!svg) return
    const blob = new Blob([svg], { type: 'image/svg+xml;charset=utf-8' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href     = url
    const slug = settings.text.slice(0, 20).replace(/\s+/g, '_').replace(/[^a-zA-Zа-яА-Я0-9_]/g, '') || 'braille'
    a.download = `braille_${slug}.svg`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }, [getSVGString, settings.text])

  const copySVG = useCallback(async () => {
    const svg = getSVGString()
    if (!svg) return
    await navigator.clipboard.writeText(svg)
  }, [getSVGString])

  return { exportSVG, copySVG }
}
